name: "FastConformer-CTC-BPE"

model:
  init_alpha_ssl: 0.0
  increase_rate_alpha_ssl: 0.0000167

  kd_teacher_path: 
  init_alpha_kd: 0.0
  increase_rate_alpha_kd: 0.6

  kd:
    kd_pairs:
      - teacher: encoder.layers.12.norm_out
        student: encoder.layers.8.norm_out
        t_dim: 1024
        s_dim: 512
      - teacher: encoder.layers.23.norm_out
        student: encoder.layers.16.norm_out
        t_dim: 1024
        s_dim: 512

  ctc:
    sample_rate: 16000
    log_prediction: true
    ctc_reduction: 'mean_volume'
    skip_nan_grad: false

    train_ds:
      manifest_filepath: 
      sample_rate: ${model.ctc.sample_rate}
      batch_size: 64
      shuffle: true
      num_workers: 8
      pin_memory: true
      max_duration: 16.7
      min_duration: 0.1
      is_tarred: false
      tarred_audio_filepaths: null
      shuffle_n: 2048
      bucketing_strategy: "fully_randomized"
      bucketing_batch_size: null

    kd_train_ds:
      manifest_filepath: 
      sample_rate: ${model.ctc.sample_rate}
      batch_size: 256
      shuffle: true
      num_workers: 8
      pin_memory: true
      max_duration: 16.7 
      min_duration: 0.1
      is_tarred: false
      tarred_audio_filepaths: null
      shuffle_n: 2048
      bucketing_strategy: "fully_randomized"
      bucketing_batch_size: null

    validation_ds:
      manifest_filepath: 
      sample_rate: ${model.ctc.sample_rate}
      batch_size: 64 
      shuffle: false
      use_start_end_token: false
      num_workers: 8
      pin_memory: true

    test_ds:
      manifest_filepath: 
      sample_rate: ${model.ctc.sample_rate}
      batch_size: 64 
      shuffle: false
      use_start_end_token: false
      num_workers: 8
      pin_memory: true

    tokenizer:
      dir:
      type: bpe

    preprocessor:
      _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
      sample_rate: ${model.ctc.sample_rate}
      normalize: "per_feature"
      window_size: 0.025
      window_stride: 0.01
      window: "hann"
      features: 80
      n_fft: 512
      log: true
      frame_splicing: 1
      dither: 0.00001
      pad_to: 0
      pad_value: 0.0

    spec_augment:
      _target_: nemo.collections.asr.modules.SpectrogramAugmentation
      freq_masks: 2
      time_masks: 10
      freq_width: 27
      time_width: 0.05

    encoder:
      _target_: nemo.collections.asr.modules.ConformerEncoder
      feat_in: ${model.ctc.preprocessor.features}
      feat_out: -1
      n_layers: 18
      d_model: 512

      subsampling: dw_striding
      subsampling_factor: 8
      subsampling_conv_channels: 256
      causal_downsampling: false

      ff_expansion_factor: 4

      self_attention_model: rel_pos
      n_heads: 8
      att_context_size: [-1, -1]
      att_context_style: regular
      xscaling: true
      untie_biases: true
      pos_emb_max_len: 5000
      use_pytorch_sdpa: false
      use_pytorch_sdpa_backends: []

      conv_kernel_size: 9
      conv_norm_type: 'batch_norm'
      conv_context_size: null

      dropout: 0.1
      dropout_pre_encoder: 0.1
      dropout_emb: 0.0
      dropout_att: 0.1

      stochastic_depth_drop_prob: 0.0
      stochastic_depth_mode: linear
      stochastic_depth_start_layer: 1

    decoder:
      _target_: nemo.collections.asr.modules.ConvASRDecoder
      feat_in: null
      num_classes: -1
      vocabulary: []

    interctc:
      loss_weights: []
      apply_at_layers: []

    optim:
      name: adamw
      lr: 1e-3
      betas: [0.9, 0.98]
      weight_decay: 1e-3

      sched:
        name: CosineAnnealing
        warmup_ratio: 0.2
        max_steps: 66300
        min_lr: 1e-4
  ssl:
    sample_rate: 16000

    train_ds:
      manifest_filepath:
      sample_rate: ${model.ssl.sample_rate}
      batch_size: 64
      shuffle: true
      num_workers: 8
      pin_memory: false
      use_start_end_token: true
      trim_silence: false
      max_duration: 16.7
      min_duration: 8.0
      is_tarred: false
      tarred_audio_filepaths: null
      shuffle_n: 2048
      bucketing_strategy: "synced_randomized"
      bucketing_batch_size: null

    validation_ds:
      manifest_filepath: "/home/at0122/austin0302.ee12/workspace/Conformer_CTC/manifest/test_other.json"
      sample_rate: ${model.ssl.sample_rate}
      batch_size: 64
      shuffle: false
      num_workers: 8
      pin_memory: true
      use_start_end_token: false
      min_duration: 8.0

    preprocessor:
      _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
      sample_rate: ${model.ssl.sample_rate}
      normalize: "per_feature"
      window_size: 0.025
      window_stride: 0.01
      window: "hann"
      features: 80
      n_fft: 512
      log: true
      frame_splicing: 1
      dither: 0.00001
      pad_to: 16
      pad_value: 0.0

    spec_augment:
      _target_: nemo.collections.asr.modules.MaskedPatchAugmentation
      freq_masks: 3
      freq_width: 20
      patch_size: 48
      mask_patches: 0.5

    encoder:
      _target_: nemo.collections.asr.modules.ConformerEncoder
      feat_in: ${model.ssl.preprocessor.features}
      feat_out: -1
      n_layers: 18
      d_model: 512
      use_bias: True

      subsampling: dw_striding
      subsampling_factor: 8
      subsampling_conv_channels: 256
      causal_downsampling: false

      reduction: null
      reduction_position: null
      reduction_factor: 1

      ff_expansion_factor: 4

      self_attention_model: rel_pos
      n_heads: 8
      att_context_size: [-1, -1]
      xscaling: true
      untie_biases: true
      pos_emb_max_len: 5000

      conv_kernel_size: 9
      conv_norm_type: 'batch_norm'
      conv_context_size: null

      dropout: 0.1
      dropout_pre_encoder: 0.1
      dropout_emb: 0.0
      dropout_att: 0.1

      stochastic_depth_drop_prob: 0.0
      stochastic_depth_mode: linear
      stochastic_depth_start_layer: 1

    decoder_out: 256

    loss_list:
      contrastive:
        is_active: true
        decoder:
          _target_: nemo.collections.asr.modules.ConvASRDecoderReconstruction
          feat_in: ${model.ssl.encoder.d_model}
          feat_hidden: ${model.ssl.decoder_out}
          feat_out: ${model.ssl.decoder_out}
          stride_layers: 0
          non_stride_layers: 0
        loss:
          _target_: nemo.collections.asr.losses.ContrastiveLoss
          in_dim: ${model.ssl.preprocessor.features}
          proj_dim: ${model.ssl.decoder_out}
          combine_time_steps: 8
          quantized_targets: false
          codebook_size: 300
          num_groups: 2
          num_negatives: 50
          sample_from_same_utterance_only: true
          sample_from_non_masked: false

      mlm:
        is_active: false
        decoder:
          _target_: nemo.collections.asr.modules.ConvASRDecoder
          feat_in: ${model.ssl.encoder.d_model}
          num_classes: 90000
        loss:
          _target_: nemo.collections.asr.losses.MLMLoss
          combine_time_steps: 4
        targets_from_loss: "contrastive"
        loss_alpha: 1000.
        transpose_encoded: false
        start_step: 0
        output_from_layer: null
    
    optim:
      name: adamw
      lr: 1e-3
      betas: [0.9, 0.98]
      weight_decay: 1e-3

      sched:
        name: CosineAnnealing
        warmup_ratio: 0.2
        min_lr: 1e-4

trainer:
  devices: 1
  num_nodes: 1
  max_epochs: 300
  max_steps: -1
  val_check_interval: 1.0
  accelerator: auto
  strategy: ddp_find_unused_parameters_true
  accumulate_grad_batches: 2
  gradient_clip_val: 0.0
  precision: bf16
  log_every_n_steps: 10
  enable_progress_bar: True
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  sync_batchnorm: true
  enable_checkpointing: False
  logger: false
  benchmark: false

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: "val_wer"
    mode: "min"
    save_top_k: 5
    always_save_nemo: True

  resume_from_checkpoint: null
  resume_if_exists: false
  resume_ignore_no_checkpoint: false

  create_wandb_logger: true
  wandb_logger_kwargs:
    name: 
    project: 